// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package watchoutdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID   int32
	Name pgtype.Text
	Cid  int32
}

type Event struct {
	Eid         int32
	Title       pgtype.Text
	Description pgtype.Text
	Time        pgtype.Timestamp
	Game        int32
	Owner       string
}

type Favoriteevent struct {
	Fid    int32
	Event  int32
	Userid string
}

type Favoritegame struct {
	Fid    int32
	Game   int32
	Userid string
}

type Favoriteowner struct {
	Fid     int32
	Ownerid string
	Userid  string
}

type Favoriteteam struct {
	Fid    int32
	Team   int32
	Userid string
}

type Game struct {
	ID    int32
	Time  pgtype.Timestamp
	Type  string
	Title string
	Team1 int32
	Team2 int32
	Gid   int32
}

type Owner struct {
	ID      int32
	Name    pgtype.Text
	Zip     pgtype.Text
	Address pgtype.Text
	City    pgtype.Text
	State   pgtype.Text
	Country pgtype.Text
	Lat     pgtype.Float8
	Long    pgtype.Float8
	Hours   pgtype.Text
	Oid     string
}

type Schedule struct {
	ID        int32
	Game      int32
	Channel   int32
	Starttime pgtype.Timestamp
	Endtime   pgtype.Timestamp
}

type Team struct {
	ID   int32
	Name pgtype.Text
	Tid  int32
}

type Transmission struct {
	Tid         int32
	Description pgtype.Text
	Owner       string
	Channel     int32
}

type User struct {
	ID   int32
	Name string
	Zip  pgtype.Text
	Uid  string
}
