// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package watchoutdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (
	name,cid
) VALUES (
	$1, $2
) RETURNING id, name, cid
`

type CreateChannelParams struct {
	Name pgtype.Text
	Cid  int32
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.Name, arg.Cid)
	var i Channel
	err := row.Scan(&i.ID, &i.Name, &i.Cid)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO users (
	name, 
	zip, 
	uid
) VALUES (
	$1, $2, $3
) RETURNING id, name, zip, uid
`

type CreateCustomerParams struct {
	Name string
	Zip  pgtype.Text
	Uid  string
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (User, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Name, arg.Zip, arg.Uid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Zip,
		&i.Uid,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
	title,
	description,
	time,
	game,
	owner
) VALUES (
	$1, $2 ,$3 ,$4 ,$5
) RETURNING eid, title, description, time, game, owner
`

type CreateEventParams struct {
	Title       pgtype.Text
	Description pgtype.Text
	Time        pgtype.Timestamp
	Game        int32
	Owner       string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.Time,
		arg.Game,
		arg.Owner,
	)
	var i Event
	err := row.Scan(
		&i.Eid,
		&i.Title,
		&i.Description,
		&i.Time,
		&i.Game,
		&i.Owner,
	)
	return i, err
}

const createFavoriteEvent = `-- name: CreateFavoriteEvent :one
INSERT INTO favoriteevents (
	event, 
	userid
) VALUES (
	$1, $2
) RETURNING fid, event, userid
`

type CreateFavoriteEventParams struct {
	Event  int32
	Userid string
}

func (q *Queries) CreateFavoriteEvent(ctx context.Context, arg CreateFavoriteEventParams) (Favoriteevent, error) {
	row := q.db.QueryRow(ctx, createFavoriteEvent, arg.Event, arg.Userid)
	var i Favoriteevent
	err := row.Scan(&i.Fid, &i.Event, &i.Userid)
	return i, err
}

const createFavoriteGame = `-- name: CreateFavoriteGame :one
INSERT INTO favoritegames (
	game, 
	userid
) VALUES (
	$1, $2
) RETURNING fid, game, userid
`

type CreateFavoriteGameParams struct {
	Game   int32
	Userid string
}

func (q *Queries) CreateFavoriteGame(ctx context.Context, arg CreateFavoriteGameParams) (Favoritegame, error) {
	row := q.db.QueryRow(ctx, createFavoriteGame, arg.Game, arg.Userid)
	var i Favoritegame
	err := row.Scan(&i.Fid, &i.Game, &i.Userid)
	return i, err
}

const createFavoriteOwner = `-- name: CreateFavoriteOwner :one
INSERT INTO favoriteowners (
	ownerid, 
	userid
) VALUES (
	$1, $2
) RETURNING fid, ownerid, userid
`

type CreateFavoriteOwnerParams struct {
	Ownerid string
	Userid  string
}

func (q *Queries) CreateFavoriteOwner(ctx context.Context, arg CreateFavoriteOwnerParams) (Favoriteowner, error) {
	row := q.db.QueryRow(ctx, createFavoriteOwner, arg.Ownerid, arg.Userid)
	var i Favoriteowner
	err := row.Scan(&i.Fid, &i.Ownerid, &i.Userid)
	return i, err
}

const createFavoriteTeam = `-- name: CreateFavoriteTeam :one
INSERT INTO favoriteteams (
	team, 
	userid
) VALUES (
	$1, $2
) RETURNING fid, team, userid
`

type CreateFavoriteTeamParams struct {
	Team   int32
	Userid string
}

func (q *Queries) CreateFavoriteTeam(ctx context.Context, arg CreateFavoriteTeamParams) (Favoriteteam, error) {
	row := q.db.QueryRow(ctx, createFavoriteTeam, arg.Team, arg.Userid)
	var i Favoriteteam
	err := row.Scan(&i.Fid, &i.Team, &i.Userid)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (
	time, 
	type,
	title,
	team1,
	team2,
	gid
) VALUES (
	$1,$2,$3,$4,$5,$6
) RETURNING id, time, type, title, team1, team2, gid
`

type CreateGameParams struct {
	Time  pgtype.Timestamp
	Type  string
	Title string
	Team1 int32
	Team2 int32
	Gid   int32
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.Time,
		arg.Type,
		arg.Title,
		arg.Team1,
		arg.Team2,
		arg.Gid,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Time,
		&i.Type,
		&i.Title,
		&i.Team1,
		&i.Team2,
		&i.Gid,
	)
	return i, err
}

const createOwner = `-- name: CreateOwner :one
INSERT INTO owners (
	name,
	zip,
	address,
	city,
	state,
	country,
	lat,
	long,
	hours, 
	oid
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, name, zip, address, city, state, country, lat, long, hours, oid
`

type CreateOwnerParams struct {
	Name    pgtype.Text
	Zip     pgtype.Text
	Address pgtype.Text
	City    pgtype.Text
	State   pgtype.Text
	Country pgtype.Text
	Lat     pgtype.Float8
	Long    pgtype.Float8
	Hours   pgtype.Text
	Oid     string
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (Owner, error) {
	row := q.db.QueryRow(ctx, createOwner,
		arg.Name,
		arg.Zip,
		arg.Address,
		arg.City,
		arg.State,
		arg.Country,
		arg.Lat,
		arg.Long,
		arg.Hours,
		arg.Oid,
	)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Zip,
		&i.Address,
		&i.City,
		&i.State,
		&i.Country,
		&i.Lat,
		&i.Long,
		&i.Hours,
		&i.Oid,
	)
	return i, err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules(
	game,
	channel,
	starttime,
	endtime
) VALUES (
	$1, $2, $3, $4
) RETURNING id, game, channel, starttime, endtime
`

type CreateScheduleParams struct {
	Game      int32
	Channel   int32
	Starttime pgtype.Timestamp
	Endtime   pgtype.Timestamp
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.Game,
		arg.Channel,
		arg.Starttime,
		arg.Endtime,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Game,
		&i.Channel,
		&i.Starttime,
		&i.Endtime,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
	name,tid
) VALUES (
	$1, $2
) RETURNING id, name, tid
`

type CreateTeamParams struct {
	Name pgtype.Text
	Tid  int32
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Tid)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.Tid)
	return i, err
}

const createTransmission = `-- name: CreateTransmission :one
INSERT INTO transmissions (
	channel,
	owner,
	description
) VALUES (
	$1, $2, $3
) RETURNING tid, description, owner, channel
`

type CreateTransmissionParams struct {
	Channel     int32
	Owner       string
	Description pgtype.Text
}

func (q *Queries) CreateTransmission(ctx context.Context, arg CreateTransmissionParams) (Transmission, error) {
	row := q.db.QueryRow(ctx, createTransmission, arg.Channel, arg.Owner, arg.Description)
	var i Transmission
	err := row.Scan(
		&i.Tid,
		&i.Description,
		&i.Owner,
		&i.Channel,
	)
	return i, err
}

const deleteAllChannels = `-- name: DeleteAllChannels :exec
TRUNCATE TABLE channels RESTART IDENTITY CASCADE
`

func (q *Queries) DeleteAllChannels(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllChannels)
	return err
}

const deleteAllEvents = `-- name: DeleteAllEvents :exec
TRUNCATE TABLE events RESTART IDENTITY CASCADE
`

func (q *Queries) DeleteAllEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllEvents)
	return err
}

const deleteAllFavorites = `-- name: DeleteAllFavorites :exec
TRUNCATE TABLE favoritegames RESTART IDENTITY CASCADE
`

func (q *Queries) DeleteAllFavorites(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllFavorites)
	return err
}

const deleteAllGames = `-- name: DeleteAllGames :exec
TRUNCATE TABLE games RESTART IDENTITY CASCADE
`

func (q *Queries) DeleteAllGames(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllGames)
	return err
}

const deleteAllOwners = `-- name: DeleteAllOwners :exec
TRUNCATE TABLE owners RESTART IDENTITY CASCADE
`

func (q *Queries) DeleteAllOwners(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllOwners)
	return err
}

const deleteAllTeams = `-- name: DeleteAllTeams :exec
TRUNCATE TABLE teams RESTART IDENTITY CASCADE
`

func (q *Queries) DeleteAllTeams(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllTeams)
	return err
}

const deleteAllTransmissions = `-- name: DeleteAllTransmissions :exec
TRUNCATE TABLE transmissions RESTART IDENTITY CASCADE
`

func (q *Queries) DeleteAllTransmissions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllTransmissions)
	return err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
TRUNCATE TABLE users RESTART IDENTITY CASCADE
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllUsers)
	return err
}

const deleteEventById = `-- name: DeleteEventById :exec
DELETE FROM events 
WHERE eid = $1
`

func (q *Queries) DeleteEventById(ctx context.Context, eid int32) error {
	_, err := q.db.Exec(ctx, deleteEventById, eid)
	return err
}

const deleteFavoriteEvent = `-- name: DeleteFavoriteEvent :exec
DELETE FROM favoriteevents
WHERE event = $1 AND userid = $2
`

type DeleteFavoriteEventParams struct {
	Event  int32
	Userid string
}

func (q *Queries) DeleteFavoriteEvent(ctx context.Context, arg DeleteFavoriteEventParams) error {
	_, err := q.db.Exec(ctx, deleteFavoriteEvent, arg.Event, arg.Userid)
	return err
}

const deleteFavoriteGame = `-- name: DeleteFavoriteGame :exec
DELETE FROM favoritegames
WHERE game = $1 AND userid = $2
`

type DeleteFavoriteGameParams struct {
	Game   int32
	Userid string
}

func (q *Queries) DeleteFavoriteGame(ctx context.Context, arg DeleteFavoriteGameParams) error {
	_, err := q.db.Exec(ctx, deleteFavoriteGame, arg.Game, arg.Userid)
	return err
}

const deleteFavoriteOwner = `-- name: DeleteFavoriteOwner :exec
DELETE FROM favoriteowners
WHERE ownerid = $1 AND userid = $2
`

type DeleteFavoriteOwnerParams struct {
	Ownerid string
	Userid  string
}

func (q *Queries) DeleteFavoriteOwner(ctx context.Context, arg DeleteFavoriteOwnerParams) error {
	_, err := q.db.Exec(ctx, deleteFavoriteOwner, arg.Ownerid, arg.Userid)
	return err
}

const deleteFavoriteTeam = `-- name: DeleteFavoriteTeam :exec
DELETE FROM favoriteteams
WHERE team = $1 AND userid = $2
`

type DeleteFavoriteTeamParams struct {
	Team   int32
	Userid string
}

func (q *Queries) DeleteFavoriteTeam(ctx context.Context, arg DeleteFavoriteTeamParams) error {
	_, err := q.db.Exec(ctx, deleteFavoriteTeam, arg.Team, arg.Userid)
	return err
}

const deleteTransmission = `-- name: DeleteTransmission :exec
DELETE FROM transmissions 
WHERE tid = $1
`

func (q *Queries) DeleteTransmission(ctx context.Context, tid int32) error {
	_, err := q.db.Exec(ctx, deleteTransmission, tid)
	return err
}

const findBarByName = `-- name: FindBarByName :many
SELECT id, name, zip, address, city, state, country, lat, long, hours, oid FROM owners
WHERE name ilike '%' || $1 || '%'
`

func (q *Queries) FindBarByName(ctx context.Context, dollar_1 pgtype.Text) ([]Owner, error) {
	rows, err := q.db.Query(ctx, findBarByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Owner
	for rows.Next() {
		var i Owner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Zip,
			&i.Address,
			&i.City,
			&i.State,
			&i.Country,
			&i.Lat,
			&i.Long,
			&i.Hours,
			&i.Oid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findChannelByName = `-- name: FindChannelByName :one
SELECT id, name, cid FROM channels
WHERE name = $1
`

func (q *Queries) FindChannelByName(ctx context.Context, name pgtype.Text) (Channel, error) {
	row := q.db.QueryRow(ctx, findChannelByName, name)
	var i Channel
	err := row.Scan(&i.ID, &i.Name, &i.Cid)
	return i, err
}

const findChannelByString = `-- name: FindChannelByString :many
SELECT id, name, cid FROM channels
WHERE name ilike '%' || $1 || '%'
`

func (q *Queries) FindChannelByString(ctx context.Context, dollar_1 pgtype.Text) ([]Channel, error) {
	rows, err := q.db.Query(ctx, findChannelByString, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(&i.ID, &i.Name, &i.Cid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventByGameId = `-- name: FindEventByGameId :many
SELECT eid,title,description, time, game, owner, ownername, gametitle,
CASE
	WHEN fe.fid IS NULL THEN FALSE
	ELSE TRUE
	END AS is_fav,
CASE
	WHEN fid IS NULL THEN -1
	ELSE fid
	END AS fid
FROM (SELECT e.eid, e.title, e.description, e.time, e.game, e.owner, o.name as ownername, g.title as gametitle
FROM events as e
JOIN owners as o
ON e.owner = o.oid
JOIN games as g
ON e.game = g.gid
WHERE e.game =$1) as events 
LEFT JOIN (SELECT fid, event,userid from favoriteevents WHERE userid=$2 ) as fe on eid = fe.event
`

type FindEventByGameIdParams struct {
	Game   int32
	Userid string
}

type FindEventByGameIdRow struct {
	Eid         int32
	Title       pgtype.Text
	Description pgtype.Text
	Time        pgtype.Timestamp
	Game        int32
	Owner       string
	Ownername   pgtype.Text
	Gametitle   string
	IsFav       bool
	Fid         interface{}
}

func (q *Queries) FindEventByGameId(ctx context.Context, arg FindEventByGameIdParams) ([]FindEventByGameIdRow, error) {
	rows, err := q.db.Query(ctx, findEventByGameId, arg.Game, arg.Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEventByGameIdRow
	for rows.Next() {
		var i FindEventByGameIdRow
		if err := rows.Scan(
			&i.Eid,
			&i.Title,
			&i.Description,
			&i.Time,
			&i.Game,
			&i.Owner,
			&i.Ownername,
			&i.Gametitle,
			&i.IsFav,
			&i.Fid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventByGameTitle = `-- name: FindEventByGameTitle :many
SELECT e.title, e.description, e.time FROM events as e 
JOIN games AS g
ON game = g.gid
WHERE g.title = $1
`

type FindEventByGameTitleRow struct {
	Title       pgtype.Text
	Description pgtype.Text
	Time        pgtype.Timestamp
}

func (q *Queries) FindEventByGameTitle(ctx context.Context, title string) ([]FindEventByGameTitleRow, error) {
	rows, err := q.db.Query(ctx, findEventByGameTitle, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEventByGameTitleRow
	for rows.Next() {
		var i FindEventByGameTitleRow
		if err := rows.Scan(&i.Title, &i.Description, &i.Time); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventByTitle = `-- name: FindEventByTitle :many
SELECT e.eid, e.title, e.description, e.time, e.game, e.owner, o.name as ownername, g.title as gametitle FROM events as e
JOIN owners as o
ON e.owner=o.oid
JOIN games as g
ON e.game = g.gid
WHERE e.title ilike '%' || $1 || '%'
`

type FindEventByTitleRow struct {
	Eid         int32
	Title       pgtype.Text
	Description pgtype.Text
	Time        pgtype.Timestamp
	Game        int32
	Owner       string
	Ownername   pgtype.Text
	Gametitle   string
}

func (q *Queries) FindEventByTitle(ctx context.Context, dollar_1 pgtype.Text) ([]FindEventByTitleRow, error) {
	rows, err := q.db.Query(ctx, findEventByTitle, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEventByTitleRow
	for rows.Next() {
		var i FindEventByTitleRow
		if err := rows.Scan(
			&i.Eid,
			&i.Title,
			&i.Description,
			&i.Time,
			&i.Game,
			&i.Owner,
			&i.Ownername,
			&i.Gametitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventPrefix = `-- name: FindEventPrefix :many
SELECT e.eid, e.title as eventtitle, e.description as eventdescription, e.time, e.game, e.owner, games.title as gametitle, o.name as ownername,
CASE
	WHEN fav.fid IS NULL THEN FALSE
	ELSE TRUE
	END AS is_fav
FROM events as e
JOIN owners as o ON e.owner = o.oid
JOIN games ON e.game = games.gid
LEFT JOIN favoriteevents AS fav ON fav.userid=$2 AND fav.event = e.eid
WHERE e.title ilike '%' || $1 || '%'
`

type FindEventPrefixParams struct {
	Column1 pgtype.Text
	Userid  string
}

type FindEventPrefixRow struct {
	Eid              int32
	Eventtitle       pgtype.Text
	Eventdescription pgtype.Text
	Time             pgtype.Timestamp
	Game             int32
	Owner            string
	Gametitle        string
	Ownername        pgtype.Text
	IsFav            bool
}

func (q *Queries) FindEventPrefix(ctx context.Context, arg FindEventPrefixParams) ([]FindEventPrefixRow, error) {
	rows, err := q.db.Query(ctx, findEventPrefix, arg.Column1, arg.Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEventPrefixRow
	for rows.Next() {
		var i FindEventPrefixRow
		if err := rows.Scan(
			&i.Eid,
			&i.Eventtitle,
			&i.Eventdescription,
			&i.Time,
			&i.Game,
			&i.Owner,
			&i.Gametitle,
			&i.Ownername,
			&i.IsFav,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventsByOwner = `-- name: FindEventsByOwner :many
SELECT g.title as gameTitle, e.title as eventTitle, e.description, e.time, e.eid
FROM events as e JOIN owners as o ON e.owner=o.oid
JOIN games as g on g.gid=e.game
WHERE o.oid = $1
`

type FindEventsByOwnerRow struct {
	Gametitle   string
	Eventtitle  pgtype.Text
	Description pgtype.Text
	Time        pgtype.Timestamp
	Eid         int32
}

func (q *Queries) FindEventsByOwner(ctx context.Context, oid string) ([]FindEventsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, findEventsByOwner, oid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEventsByOwnerRow
	for rows.Next() {
		var i FindEventsByOwnerRow
		if err := rows.Scan(
			&i.Gametitle,
			&i.Eventtitle,
			&i.Description,
			&i.Time,
			&i.Eid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFavoriteEvent = `-- name: FindFavoriteEvent :many
SELECT 
  e.eid, 
  e.title AS eventtitle, 
  e.description AS eventdescription, 
  e.time, 
  e.game, 
  e.owner, 
  o.name as ownername,
  g.title as gametitle
FROM favoriteevents AS f
JOIN events AS e ON f.event = e.eid
JOIN owners AS o ON e.owner = o.oid 
JOIN games as g on e.game = g.gid
WHERE f.userid = $1
`

type FindFavoriteEventRow struct {
	Eid              int32
	Eventtitle       pgtype.Text
	Eventdescription pgtype.Text
	Time             pgtype.Timestamp
	Game             int32
	Owner            string
	Ownername        pgtype.Text
	Gametitle        string
}

func (q *Queries) FindFavoriteEvent(ctx context.Context, userid string) ([]FindFavoriteEventRow, error) {
	rows, err := q.db.Query(ctx, findFavoriteEvent, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFavoriteEventRow
	for rows.Next() {
		var i FindFavoriteEventRow
		if err := rows.Scan(
			&i.Eid,
			&i.Eventtitle,
			&i.Eventdescription,
			&i.Time,
			&i.Game,
			&i.Owner,
			&i.Ownername,
			&i.Gametitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFavoriteGame = `-- name: FindFavoriteGame :many
SELECT g.title as gametitle, g.time as gametime, f.fid, g.gid, g.title, g.type FROM favoritegames as f
JOIN games as g
ON f.game = g.gid
WHERE userid = $1
`

type FindFavoriteGameRow struct {
	Gametitle string
	Gametime  pgtype.Timestamp
	Fid       int32
	Gid       int32
	Title     string
	Type      string
}

func (q *Queries) FindFavoriteGame(ctx context.Context, userid string) ([]FindFavoriteGameRow, error) {
	rows, err := q.db.Query(ctx, findFavoriteGame, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFavoriteGameRow
	for rows.Next() {
		var i FindFavoriteGameRow
		if err := rows.Scan(
			&i.Gametitle,
			&i.Gametime,
			&i.Fid,
			&i.Gid,
			&i.Title,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFavoriteOwner = `-- name: FindFavoriteOwner :many
SELECT o.name as ownername, f.fid, o.oid FROM favoriteowners as f
JOIN owners as o
ON f.ownerid = o.oid
WHERE userid = $1
`

type FindFavoriteOwnerRow struct {
	Ownername pgtype.Text
	Fid       int32
	Oid       string
}

func (q *Queries) FindFavoriteOwner(ctx context.Context, userid string) ([]FindFavoriteOwnerRow, error) {
	rows, err := q.db.Query(ctx, findFavoriteOwner, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFavoriteOwnerRow
	for rows.Next() {
		var i FindFavoriteOwnerRow
		if err := rows.Scan(&i.Ownername, &i.Fid, &i.Oid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFavoriteTeam = `-- name: FindFavoriteTeam :many
SELECT t.name as teamtitle, f.fid, t.tid FROM favoriteteams as f
JOIN teams as t
ON f.team = t.tid
WHERE userid = $1
`

type FindFavoriteTeamRow struct {
	Teamtitle pgtype.Text
	Fid       int32
	Tid       int32
}

func (q *Queries) FindFavoriteTeam(ctx context.Context, userid string) ([]FindFavoriteTeamRow, error) {
	rows, err := q.db.Query(ctx, findFavoriteTeam, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFavoriteTeamRow
	for rows.Next() {
		var i FindFavoriteTeamRow
		if err := rows.Scan(&i.Teamtitle, &i.Fid, &i.Tid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGameByTitle = `-- name: FindGameByTitle :one
SELECT id, time, type, title, team1, team2, gid FROM games
WHERE title = $1
`

func (q *Queries) FindGameByTitle(ctx context.Context, title string) (Game, error) {
	row := q.db.QueryRow(ctx, findGameByTitle, title)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Time,
		&i.Type,
		&i.Title,
		&i.Team1,
		&i.Team2,
		&i.Gid,
	)
	return i, err
}

const findGameLikeCount = `-- name: FindGameLikeCount :many
SELECT game, count, id, time, type, title, team1, team2, gid FROM (SELECT game, COUNT(game) FROM favoritegames
GROUP BY game ) as favCnt JOIN games as g ON favCnt.game=g.gid 
WHERE title ilike '%' || $1 || '%'
`

type FindGameLikeCountRow struct {
	Game  int32
	Count int64
	ID    int32
	Time  pgtype.Timestamp
	Type  string
	Title string
	Team1 int32
	Team2 int32
	Gid   int32
}

func (q *Queries) FindGameLikeCount(ctx context.Context, dollar_1 pgtype.Text) ([]FindGameLikeCountRow, error) {
	rows, err := q.db.Query(ctx, findGameLikeCount, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindGameLikeCountRow
	for rows.Next() {
		var i FindGameLikeCountRow
		if err := rows.Scan(
			&i.Game,
			&i.Count,
			&i.ID,
			&i.Time,
			&i.Type,
			&i.Title,
			&i.Team1,
			&i.Team2,
			&i.Gid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGamePrefix = `-- name: FindGamePrefix :many
SELECT DISTINCT on (gid) t1.name AS team1, t2.name AS team2, type, time, title, gid, type,
CASE
	WHEN fid IS NULL THEN FALSE
	ELSE TRUE
	END AS is_fav
FROM games
JOIN teams AS t1 on t1.tid=games.team1 or t1.tid=games.team2
JOIN teams AS t2 on (t2.tid=games.team1 or t2.tid=games.team2) AND t1.tid != t2.tid
LEFT JOIN favoritegames AS fav on (fav.userid=$2) AND (fav.game = gid)
WHERE title ilike '%' || $1 || '%'
`

type FindGamePrefixParams struct {
	Column1 pgtype.Text
	Userid  string
}

type FindGamePrefixRow struct {
	Team1  pgtype.Text
	Team2  pgtype.Text
	Type   string
	Time   pgtype.Timestamp
	Title  string
	Gid    int32
	Type_2 string
	IsFav  bool
}

func (q *Queries) FindGamePrefix(ctx context.Context, arg FindGamePrefixParams) ([]FindGamePrefixRow, error) {
	rows, err := q.db.Query(ctx, findGamePrefix, arg.Column1, arg.Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindGamePrefixRow
	for rows.Next() {
		var i FindGamePrefixRow
		if err := rows.Scan(
			&i.Team1,
			&i.Team2,
			&i.Type,
			&i.Time,
			&i.Title,
			&i.Gid,
			&i.Type_2,
			&i.IsFav,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOwnerById = `-- name: FindOwnerById :one
SELECT id, name, zip, address, city, state, country, lat, long, hours, oid FROM owners
WHERE oid = $1
`

func (q *Queries) FindOwnerById(ctx context.Context, oid string) (Owner, error) {
	row := q.db.QueryRow(ctx, findOwnerById, oid)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Zip,
		&i.Address,
		&i.City,
		&i.State,
		&i.Country,
		&i.Lat,
		&i.Long,
		&i.Hours,
		&i.Oid,
	)
	return i, err
}

const findOwnerByName = `-- name: FindOwnerByName :one
SELECT id, name, zip, address, city, state, country, lat, long, hours, oid FROM owners
WHERE name = $1
`

func (q *Queries) FindOwnerByName(ctx context.Context, name pgtype.Text) (Owner, error) {
	row := q.db.QueryRow(ctx, findOwnerByName, name)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Zip,
		&i.Address,
		&i.City,
		&i.State,
		&i.Country,
		&i.Lat,
		&i.Long,
		&i.Hours,
		&i.Oid,
	)
	return i, err
}

const findOwnerPrefix = `-- name: FindOwnerPrefix :many
SELECT id, name, zip, address, city, state, country, lat, long, hours, oid, fid, ownerid, userid,
CASE
	WHEN fav.fid IS NULL THEN FALSE
	ELSE TRUE
	END AS is_fav
FROM owners as o
LEFT JOIN favoriteowners AS fav ON fav.userid=$2 AND fav.ownerid = o.oid
WHERE o.name ilike '%' || $1 || '%'
`

type FindOwnerPrefixParams struct {
	Column1 pgtype.Text
	Userid  string
}

type FindOwnerPrefixRow struct {
	ID      int32
	Name    pgtype.Text
	Zip     pgtype.Text
	Address pgtype.Text
	City    pgtype.Text
	State   pgtype.Text
	Country pgtype.Text
	Lat     pgtype.Float8
	Long    pgtype.Float8
	Hours   pgtype.Text
	Oid     string
	Fid     pgtype.Int4
	Ownerid pgtype.Text
	Userid  pgtype.Text
	IsFav   bool
}

func (q *Queries) FindOwnerPrefix(ctx context.Context, arg FindOwnerPrefixParams) ([]FindOwnerPrefixRow, error) {
	rows, err := q.db.Query(ctx, findOwnerPrefix, arg.Column1, arg.Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindOwnerPrefixRow
	for rows.Next() {
		var i FindOwnerPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Zip,
			&i.Address,
			&i.City,
			&i.State,
			&i.Country,
			&i.Lat,
			&i.Long,
			&i.Hours,
			&i.Oid,
			&i.Fid,
			&i.Ownerid,
			&i.Userid,
			&i.IsFav,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTeam = `-- name: FindTeam :one
SELECT id, name, tid FROM teams 
WHERE name = $1
`

func (q *Queries) FindTeam(ctx context.Context, name pgtype.Text) (Team, error) {
	row := q.db.QueryRow(ctx, findTeam, name)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.Tid)
	return i, err
}

const findTeamPrefix = `-- name: FindTeamPrefix :many
SELECT DISTINCT ON (name)
    name, time,tid,
CASE
	WHEN fav.fid IS NULL THEN FALSE
	ELSE TRUE
	END AS is_fav
FROM (
    SELECT teams.name, games.time, teams.tid FROM teams 
    LEFT JOIN games ON teams.tid = games.team1 OR teams.tid = games.team2
    WHERE teams.name ILIKE '%' || $1 || '%'
) AS recent_games LEFT JOIN favoriteteams AS fav ON fav.userid=$2 AND fav.team = recent_games.tid
ORDER BY name, time DESC
`

type FindTeamPrefixParams struct {
	Column1 pgtype.Text
	Userid  string
}

type FindTeamPrefixRow struct {
	Name  pgtype.Text
	Time  pgtype.Timestamp
	Tid   int32
	IsFav bool
}

func (q *Queries) FindTeamPrefix(ctx context.Context, arg FindTeamPrefixParams) ([]FindTeamPrefixRow, error) {
	rows, err := q.db.Query(ctx, findTeamPrefix, arg.Column1, arg.Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindTeamPrefixRow
	for rows.Next() {
		var i FindTeamPrefixRow
		if err := rows.Scan(
			&i.Name,
			&i.Time,
			&i.Tid,
			&i.IsFav,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTransmissionsByOwner = `-- name: FindTransmissionsByOwner :many
SELECT t.tid, t.owner, t.channel, t.description, c.name as channelname FROM transmissions as t
JOIN channels as c 
ON t.channel = c.cid
WHERE owner = $1
`

type FindTransmissionsByOwnerRow struct {
	Tid         int32
	Owner       string
	Channel     int32
	Description pgtype.Text
	Channelname pgtype.Text
}

func (q *Queries) FindTransmissionsByOwner(ctx context.Context, owner string) ([]FindTransmissionsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, findTransmissionsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindTransmissionsByOwnerRow
	for rows.Next() {
		var i FindTransmissionsByOwnerRow
		if err := rows.Scan(
			&i.Tid,
			&i.Owner,
			&i.Channel,
			&i.Description,
			&i.Channelname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserById = `-- name: FindUserById :one
SELECT id, name, zip, uid FROM users
WHERE uid = $1
`

func (q *Queries) FindUserById(ctx context.Context, uid string) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, uid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Zip,
		&i.Uid,
	)
	return i, err
}

const getEventLikeCount = `-- name: GetEventLikeCount :one
SELECT Count(*) FROM favoriteevents where event=$1
`

func (q *Queries) GetEventLikeCount(ctx context.Context, event int32) (int64, error) {
	row := q.db.QueryRow(ctx, getEventLikeCount, event)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getScheduleByChannel = `-- name: GetScheduleByChannel :many
SELECT s.id, game, channel, starttime, endtime, games.id, time, type, title, team1, team2, gid FROM (SELECT id, game, channel, starttime, endtime FROM schedules 
WHERE channel=$1 
AND $2 BETWEEN starttime AND endtime)
AS s JOIN games ON s.game = gid
`

type GetScheduleByChannelParams struct {
	Channel   int32
	Starttime pgtype.Timestamp
}

type GetScheduleByChannelRow struct {
	ID        int32
	Game      int32
	Channel   int32
	Starttime pgtype.Timestamp
	Endtime   pgtype.Timestamp
	ID_2      int32
	Time      pgtype.Timestamp
	Type      string
	Title     string
	Team1     int32
	Team2     int32
	Gid       int32
}

func (q *Queries) GetScheduleByChannel(ctx context.Context, arg GetScheduleByChannelParams) ([]GetScheduleByChannelRow, error) {
	rows, err := q.db.Query(ctx, getScheduleByChannel, arg.Channel, arg.Starttime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScheduleByChannelRow
	for rows.Next() {
		var i GetScheduleByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.Game,
			&i.Channel,
			&i.Starttime,
			&i.Endtime,
			&i.ID_2,
			&i.Time,
			&i.Type,
			&i.Title,
			&i.Team1,
			&i.Team2,
			&i.Gid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
